add styles and markup for gallery
KurbatovAS/js-traning pull request #1
Opened 2021-12-01 11:10 UTC by SofiaProtsiv

![image](https://user-images.githubusercontent.com/71260387/144224182-e6f328e5-09de-4715-8467-4140f103914a.png)

2021-12-01 20:21 UTC, KurbatovAS requested changes
Молодчина, София! Поздравляю с первым пулл-реквестом! Здорово!

2021-12-01 20:21 UTC, KurbatovAS commented on src/partials/gallery.html
> +  <section class="movies container">
Привет! Поздравляю с первым пуллом тебя! :) 
Для секции думаю, лучше будет использовать общий класс "section" (я его прописал в компоненте "_section.scss"), а для переопределения стилей конкретно этой секции можно использовать второй класс-модификатор что-то типа "section--gallery" или типа того. Что скажешь?

2021-12-01 20:21 UTC, KurbatovAS commented on src/partials/gallery.html
> +    <ul class="movies__list"></ul>
Помню, Григорий рекомендовал список уже делать отдельным блоком (по БЭМ), потому моё мнение такое, что этому ul-у можно задать класс "movies", а остальным его дочерним элементам, соответственно:
movies__item
movies__poster
movies__name
movies__genre

2021-12-01 20:21 UTC, KurbatovAS commented on src/partials/gallery.html
> +      <button class='load-more is-hidden' type='button' data-action='load-more'>
Я, к стати, тоже думаю, что пагинацию нужно вынести отдельным блоком, а может даже отдельной секцией. По макету, судя по отступам, это вполне логично.

2021-12-01 20:21 UTC, KurbatovAS commented on src/sass/components/_gallery.scss
> +    transition: all 0.4s ease;
Предлагаю переходы, особенно, если они будут встречаться не единожды, прописывать через переменные. Что скажешь?

2021-12-01 20:21 UTC, KurbatovAS commented on src/sass/components/_gallery.scss
> +    color: #FF6B08;
Этот цвет уже есть в переменных ($accent-color), но ты, полагаю, его назначала ещё до того, как я переменные прописал. Верно?

2021-12-01 20:21 UTC, KurbatovAS commented on src/sass/components/_gallery.scss
> +  @media screen and (max-width: 767px) {
Для этого размера (767px) тоже уже есть переменная: $mobile-max
Если нужно, можем обсудить этот момент, как мы это будем делать.
Дальше я не буду акцентировать внимание на этих моментах. Если мы решим, что будем их прописывать через переменные, то тогда пройдись, поменяй эти размеры на переменные

2021-12-01 20:21 UTC, KurbatovAS commented on src/sass/components/_gallery.scss
> +  @media screen and (min-width: 1400px) {
А нам точно нужна эта точка перелома: 1400px ?

2021-12-01 20:21 UTC, KurbatovAS commented on src/sass/main.css
> +@charset "UTF-8";
Если я не ошибаюсь, этот файл нам не нужно пулить. Если что, я его удалю из пулл-реквеста.

2021-12-01 20:21 UTC, KurbatovAS commented on src/templates/preview_card.hbs
> +<li class="movies__list-item">
По поводу именование классов этого блока я уже писал выше в файле "gallery.html"

2021-12-02 08:10 UTC, SofiaProtsiv commented on src/sass/components/_gallery.scss
> +  @media screen and (min-width: 1400px) {
так просто карточки виглядали поестетичніше, 4 в ряд, а коли 3 вряд то повно пустого місця, якшо шо потом удалим

2021-12-02 08:11 UTC, SofiaProtsiv reviewed
Відправила повторний пул реквест

2021-12-02 08:50 UTC, KurbatovAS commented on src/sass/components/_gallery.scss
> +  @media screen and (min-width: 1400px) {
Да, наверное так будет лучше :)

2021-12-02 10:29 UTC, KurbatovAS requested changes

2021-12-02 10:29 UTC, KurbatovAS commented on src/templates/preview_card.hbs
>      <img class="movie__poster" src="https://image.tmdb.org/t/p/w500/{{poster_path}}" alt="{{title}} poster" id="{{id}}" loading="lazy" onError="this.onerror=null;this.src='https://hostiq.ua/wiki/wp-c
Элементы блока "movies" стоит переименовать на:
"movies__name"
"movies__genre"
"movies__poster"

2021-12-02 10:29 UTC, KurbatovAS commented on src/sass/components/_gallery.scss
> +.container{
Измени, пожалуйста, медиа правила. То-есть сделай медиа правила внутри селектора, а не наоборот - селектры внутри меда правила. Что бы было в одном стандарте.

2021-12-02 10:29 UTC, KurbatovAS commented on src/sass/components/_gallery.scss
> +  width: 320px;
Там где у нас ширины совпадают с шириной точек перелома, можно использовать переменные для точек перелома.

2021-12-02 10:29 UTC, KurbatovAS commented on src/partials/gallery.html
> +  <section class="section--gallery container">
Здесь, полагаю. можно было бы сделать по общему стандарту, если по другому не будет логичнее:
<section class="section section--gallery">
<div class="container container--gallery">

2021-12-02 13:27 UTC, KurbatovAS approved these changes

2021-12-02 13:27 UTC, merged