markup header
KurbatovAS/js-traning pull request #2
Opened 2021-12-01 13:28 UTC by NataliyaKulibaba

2021-12-01 20:41 UTC, KurbatovAS requested changes
Поздравляю с первым пулл-реквестом! Молодчина! Здорово!

2021-12-01 20:41 UTC, KurbatovAS commented on src/partials/header.html
> +      <input class="form__input" type="text" placeholder="Поиск фильмов">
Я вот что подумал по поводу этого плейсхолдера. У нас сайт по умолчанию на английском языке, может и плейсхолдер стоит прописать на инглише?

2021-12-01 20:41 UTC, KurbatovAS commented on src/sass/components/_header.scss
> +li {
list-style: none; у нас прописан на список в компоненте _normalize.scss, но, полагаю, ты это прописала ещё до того, как я создал этот компонент, верно? ;)

2021-12-01 20:41 UTC, KurbatovAS commented on src/sass/components/_header.scss
> +  width: 320px;
Мы вопрос - как мы будем использовать/прописывать размеры основных брейкпоинтов, не обсуждали, но есть предложение в таких случаях использовать переменные, я их в прописал в _variables.scss:

//breakpoints
$mobile: 320px;
$mobile-max: 767px;
$tablet: 768px;
$table-max: 1023px;
$desktop: 1024px;

Что думаешь по этому поводу?

2021-12-01 20:41 UTC, KurbatovAS commented on src/sass/components/_header.scss
> +  @media screen and(min-width: 768px) {
То-же самое тут. Если мы этот вопрос обсудим и решим использовать переменные в точках перелома, то тогда пройдись по коду и поизменяй, ок?

2021-12-01 20:41 UTC, KurbatovAS commented on src/sass/components/_header.scss
> +      url('/images/images-hero/Hero768.jpg');
Думаю, плохая практика в именах файлов использовать заглавные буквы "Hero768.jpg", лучше измени. Помню на первом проекте у меня с этими большими буквами в картинках была головная боль...
Просмотри, пожалуйста, и везде измени.

2021-12-01 20:41 UTC, KurbatovAS commented on src/sass/components/_header.scss
> +  font-family: Roboto;
Шрифт у нас на весь сайт только один и он прописан на body, думаю, не обязательно его переопределять локально.

2021-12-01 20:41 UTC, KurbatovAS commented on src/sass/components/_header.scss
> +  line-height: 35px;
Перепиши в виде множителя (индекса) : 1,16

2021-12-01 20:41 UTC, KurbatovAS commented on src/sass/components/_header.scss
> +  color: #ffffff;
Цвета у нас уже есть в переменных в компоненте _variables.scss
Уже можно их оттуда использовать.

// colors
$main-color: #ffffff;
$accent-color: #ff6b08;
$logo-icon-color: #818181;
$footer-bg-color: #f7f7f7;

// text colors
$white-color: #ffffff;
$black-color: #000000;
$grey-color: #8c8c8c;
$light-grey-color: #f7f7f7;
$dark-grey-color: #545454;
$red-color: #ff001b;

2021-12-01 20:41 UTC, KurbatovAS commented on src/sass/components/_header.scss
> +  color: #fff;
И тут ;)

2021-12-01 20:41 UTC, KurbatovAS commented on src/sass/components/_header.scss
> +  font-family: Roboto;
И тут...

2021-12-01 20:41 UTC, KurbatovAS commented on src/sass/components/_header.scss
> +  background-color: #ff6b08;
Полагаю, что ты цвета прописывала ещё до того, как я их в переменные определил ;)
Что бы я дальше не акцентировал на этом внимание, пройдись по коду и измени на переменные, пожалуйста.

2021-12-01 20:41 UTC, KurbatovAS commented on src/sass/components/_header.scss
> +  transition: transform 250ms cubic-bezier(0.4, 0, 0.2, 1);
Предлагаю обсудить вопрос прописывания параметров переходов в переменных. Я там это уже кое-что прописал. 
Вот:

// transition properties
$time: 250ms;
$timing-function: cubic-bezier(0.4, 0, 0.2, 1);

2021-12-01 20:51 UTC, NataliyaKulibaba commented on src/partials/header.html
> +      <input class="form__input" type="text" placeholder="Поиск фильмов">
+

2021-12-01 20:52 UTC, NataliyaKulibaba commented on src/sass/components/_header.scss
> +li {
верно. там еще несколько таких. +

2021-12-01 20:54 UTC, NataliyaKulibaba commented on src/sass/components/_header.scss
> +  width: 320px;
на самом деле ровно относительно этих переменных. Но раз прописал - давай использовать. исправлю

2021-12-01 20:54 UTC, NataliyaKulibaba commented on src/sass/components/_header.scss
> +      url('/images/images-hero/Hero768.jpg');
ок+

2021-12-01 21:06 UTC, NataliyaKulibaba commented on src/sass/components/_header.scss
> +  width: 320px;
done

2021-12-01 21:06 UTC, NataliyaKulibaba commented on src/sass/components/_header.scss
> +  @media screen and(min-width: 768px) {
done

2021-12-01 21:07 UTC, NataliyaKulibaba commented on src/sass/components/_header.scss
> +  line-height: 35px;
done

2021-12-01 21:08 UTC, NataliyaKulibaba commented on src/sass/components/_header.scss
> +  color: #ffffff;
done. только лого не трогала, оон сам по себе идет такого цвета. и переопределять не нужно (чистить спрайт), если не будет только на нем ховера или фокуса. пока не предполагалось

2021-12-01 21:08 UTC, NataliyaKulibaba commented on src/sass/components/_header.scss
> +  color: #fff;
done

2021-12-01 21:08 UTC, NataliyaKulibaba commented on src/sass/components/_header.scss
> +  font-family: Roboto;
+

2021-12-01 21:15 UTC, NataliyaKulibaba commented on src/sass/components/_header.scss
> +  background-color: #ff6b08;
+

2021-12-01 21:15 UTC, NataliyaKulibaba commented on src/sass/components/_header.scss
> +  transition: transform 250ms cubic-bezier(0.4, 0, 0.2, 1);
ready

2021-12-01 21:15 UTC, NataliyaKulibaba commented on src/sass/components/_header.scss
> +  font-family: Roboto;
+

2021-12-02 09:58 UTC, KurbatovAS requested changes

2021-12-02 09:58 UTC, KurbatovAS commented on src/sass/components/_header.scss
> +  background-image: linear-gradient(to right, rgba(47, 48, 58, 0.4), rgba(47, 48, 58, 0.4)),
Что если попробовать эти параметры :
to right, rgba(47, 48, 58, 0.4), rgba(47, 48, 58, 0.4) 
реализовать через переменную?

2021-12-02 09:58 UTC, KurbatovAS commented on src/partials/header.html
> +      <input class="form__input" type="text" placeholder="Search Movies">
Наташ, если я всё правильно понимаю, то если у тебя блок называется "search-form", то элемент блока должен называться не "form__input", а "search-form__input", верно?

2021-12-02 09:58 UTC, KurbatovAS commented on src/partials/header.html
> +        <svg class="form__icon">
и тут

2021-12-02 10:03 UTC, NataliyaKulibaba commented on src/sass/components/_header.scss
> +  background-image: linear-gradient(to right, rgba(47, 48, 58, 0.4), rgba(47, 48, 58, 0.4)),
исправила. добавила новую переменную

2021-12-02 10:05 UTC, NataliyaKulibaba commented on src/partials/header.html
> +      <input class="form__input" type="text" placeholder="Search Movies">
подправила. И в refs тоже

2021-12-02 10:05 UTC, NataliyaKulibaba commented on src/partials/header.html
> +        <svg class="form__icon">
+

2021-12-02 11:35 UTC, KurbatovAS requested changes

2021-12-02 11:35 UTC, KurbatovAS commented on src/partials/header.html
> +    <ul class="library__list is-hidden">
Ты чего элементы:
library__list
library__item
library__btn
оставила сиротами, без родителя "**library**" ?

2021-12-02 11:35 UTC, KurbatovAS commented on src/sass/components/_header.scss
> +  padding-right: 20px;
Эти падинги есть в общем классе в компоненте "_container.scss". Может логично было бы использовать общий container и просто переопределить некоторые стили модификатором "container--header" ?

2021-12-02 12:13 UTC, NataliyaKulibaba commented on src/partials/header.html
> +    <ul class="library__list is-hidden">
+

2021-12-02 12:18 UTC, NataliyaKulibaba commented on src/sass/components/_header.scss
> +  padding-right: 20px;
+

2021-12-02 12:33 UTC, KurbatovAS approved these changes

2021-12-02 12:33 UTC, KurbatovAS commented on src/partials/header.html
> +  <div class="page-header__container container">
Честно говоря, я больше склоняюсь к варианту, как нам дядя Репета говорил и Григорий его поддерживал:
<div class="container container--page-header"> но я не могу утверждать как именно правильно, потому можно оставить и так...

2021-12-02 12:33 UTC, merged